packages:
  - '.'
allowBuilds:
  '@tailwindcss/oxide': true
  core-js: true
  cypress: set this to true or false
  esbuild: true
  javascript-obfuscator: true

overrides:
  vite: "6.3.5"
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.1"
